spring:
  r2dbc:
    url: r2dbc:postgresql://ep-twilight-truth-ahkkssbj-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_QNI2aTLteqX9

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: INFO